service:
  name: aws-nodejs-typescript

# serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-offline-sqs


provider:
  name: aws
  runtime: nodejs10.x
  timeout: 300
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource: "ARN:URL"   # TODO : CHANGE HERE

functions:
  receiveMessage:
    handler: handler.receiveMessage
    events:
      - sqs:
          arn: "ARN:URL" # TODO : CHANGE HERE
          batchSize: 1